# Generated by Django 4.0.3 on 2023-01-27 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=100)),
                ('location_start', models.CharField(max_length=100)),
                ('location_end', models.CharField(max_length=100)),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('time_start', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('vehicle', models.FloatField(max_length=100)),
                ('point', models.DecimalField(decimal_places=0, max_digits=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocates', to='company.company')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
