# Generated by Django 4.0.3 on 2023-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=20)),
                ('business_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
